apibara/dna

starknet/Cargo.toml

Handle sigterm

---

node/src/chain_tracker.rs
node/src/lib.rs
node/src/reflection.rs
starknet/src/server.rs

Reflection works with grpc requests, but not grpcurl. Needs further investigation for that.

Expose starknet data through reflection

---

Cargo.lock
starknet/Cargo.toml
tonic-reflection-patched/Cargo.toml
tonic-reflection-patched/LICENSE
tonic-reflection-patched/README.md
tonic-reflection-patched/build.rs
tonic-reflection-patched/proto/reflection.proto
tonic-reflection-patched/src/lib.rs
tonic-reflection-patched/src/server.rs
tonic-reflection-patched/tests/server.rs

This is needed to make the server play nicely with grpcurl.

Return empty extensions in reflection server

---

node/src/o11y.rs

This PR enables configuring some attributes from environment variables.

Add otel resource attributes

---

Cargo.lock
starknet/Cargo.toml

This causes mainnet syncing to fail.

Parse l1 handler tx without nonce

---

node/src/chain_tracker.rs
starknet/src/block_ingestion.rs

while the starknet sequencer is centralized, it is still possible to
have what looks like chain reorgs if, for example, the l1 verifier
rejects a block.

starknet: handle chain reorgs while offline

---

starknet/src/block_ingestion.rs

- starknet: handle reorg if it shrinks chain
- starknet: print more debug information

more debug info

---

Cargo.lock
node/src/o11y.rs
starknet/Cargo.toml
starknet/src/block_ingestion.rs
starknet/src/server.rs

- starknet: output ingestion traces
- starknet: trace grpc server

Improve starknet node traces

---

starknet/src/stream/filtered.rs

Empty messages are useful to signal to the client that the stream is working, but no data was matched.

Allow empty data messages

---

Cargo.lock
Cargo.toml
sdk/Cargo.toml
sdk/build.rs
sdk/src/config.rs
sdk/src/lib.rs

Working on implementing sdk as described here : #64

feat: init sdk workspace + high level implementation api

---

sdk/src/lib.rs

Improve the api based on what I learned integrating with dojo.

sdk: improve data stream api

---

Cargo.lock
core/Cargo.toml
core/build.rs
core/src/starknet/data.rs
core/src/starknet/proto.rs
sdk/Cargo.toml
sdk/src/config.rs
starknet/Cargo.toml
starknet/src/provider.rs

Derive serde serialize and deserialize for stream types. This is the first step in creating an environment of tools that push data to different destinations.

Serialize and deserialize stream types

---

Cargo.lock
Cargo.toml
core/src/starknet/data.rs
core/src/starknet/filter.rs
examples/starknet-simple/Cargo.toml
examples/starknet-simple/src/main.rs
sdk/src/config.rs

Add an example showing how to use the Rust SDK.

Add SDK example

---

starknet/src/stream/cursor_producer.rs

If the user specified an empty hash, the node would look for that as the
starting block.

starknet: read block id from storage if only block number specified

---

Cargo.lock
Cargo.nix
Cargo.toml
sink-mongo/Cargo.toml
sink-mongo/README.md
sink-mongo/src/bin.rs
sink-mongo/src/lib.rs

[Future]: add a sink to write data to MongoDB

---

Cargo.lock
Cargo.toml
core/src/node.rs
sink-common/README.md
sink-common/src/lib.rs
sink-mongo/src/lib.rs
sink-parquet/src/lib.rs
sink-postgres/Cargo.toml
sink-postgres/README.md
sink-postgres/src/bin.rs
sink-postgres/src/lib.rs
sink-webhook/src/lib.rs

[Feature]: PostgreSQL Integration Sink

---

.devcontainer/.profile-1-link
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/nix.conf
.devcontainer/profile.sh
.github/workflows/nix.yml
.gitignore
CODEOWNERS
CONTRIBUTING.md
README.md

Add devcontainers to simplify development to users that don't have nix
installed.

Add devcontainer

---

docs/integrations/configuration.mdx
docs/integrations/index.mdx
docs/integrations/mongo.mdx
docs/integrations/parquet.mdx
docs/integrations/postgres.mdx
docs/integrations/webhook.mdx
sink-mongo/src/bin.rs
sink-parquet/src/bin.rs
sink-postgres/src/bin.rs

Add documentation for all integrations.

Add documentation for integrations

---

develop/otel-collector-config.yml
node/src/stream/data.rs
observability/src/lib.rs
starknet/src/db/block.rs
starknet/src/db/mod.rs
starknet/src/db/state.rs
starknet/src/db/storage.rs
starknet/src/db/transaction.rs
starknet/src/stream/batch_producer.rs

There is a performance issue with some specific combinations of filters/blocks. This PR improves tracing so that we can use this information to better debug the issue.

Improve data stream tracing

---

sink-webhook/src/bin.rs
sink-webhook/src/lib.rs

webhook: add raw mode to send data as is without wrapping

---

sink-common/src/connector.rs
sink-common/src/persistence.rs

Sink: Fix invalidate data

---

node/src/server/metadata.rs
node/src/stream/data.rs

**Summary**
This adds a new metric to the node that tracks the number of bytes sent to a client.

Add `stream_sent_bytes` metric

---

sink-common/src/connector.rs
sink-mongo/src/sink.rs
sink-parquet/src/sink.rs
sink-postgres/src/sink.rs
sink-webhook/src/sink.rs

[Feature]: allow integrations to control cursor persistence

---

nix/ci.nix

**Summary**
Update the CI pipeline to build more tasks in parallel, prioritizing reaching a working docker image as soon as possible.

Streamline CI pipeline

---

install/Dockerfile.test
install/README.md
install/install.sh
nix/ci.nix
nix/native.nix

**Summary**
Add a shell script to download and install the Apibara CLI tool automatically.

Add installer script

---

Cargo.lock
Cargo.toml
starknet/CHANGELOG.md
starknet/Cargo.toml
starknet/src/provider.rs

**Summary**
Update starknet-rs to use the new RPC v0.4 implementation.

starknet: update starknet-rs version

---

Cargo.lock
examples/webhook/docker-compose.yml
nix/ci.nix
script/src/script.rs
script/tests/test_transformer.rs
sink-common/tests/test_etcd_persistence.rs
sink-console/CHANGELOG.md
sink-console/Cargo.toml
sink-mongo/CHANGELOG.md
sink-mongo/Cargo.toml
sink-parquet/CHANGELOG.md
sink-parquet/Cargo.toml
sink-postgres/CHANGELOG.md
sink-postgres/Cargo.toml
sink-webhook/CHANGELOG.md
sink-webhook/Cargo.toml
sink-webhook/src/sink.rs
sink-webhook/tests/test_sink.rs

This PR is to release the sinks with the latest changes
* persist state to the file system
* transform now accepts a single block at the time

Release new sinks

---

nix/ci.nix

**Summary**
Docker-in-Docker doesn't work great in some environments. We switch to tools that don't require a Docker daemon/socket to run.

ci: Remove Docker dependency

---

Cargo.lock
cli/Cargo.toml
cli/src/main.rs
cli/src/test/error.rs
cli/src/test/mod.rs
cli/src/test/run.rs
cli/src/test/snapshot.rs
sdk/src/lib.rs
sdk/tests/test_sdk.rs
sink-common/src/cli.rs
sink-common/src/configuration.rs
sink-common/src/connector.rs
sink-common/src/lib.rs

[Test]: Add a command to test transform functions

---

Cargo.lock
core/build.rs
core/proto/quota/v1/quota.proto
core/src/lib.rs
core/src/quota.rs
node/src/server/mod.rs
node/src/server/quota.rs
node/src/stream/data.rs
node/src/stream/error.rs
starknet/CHANGELOG.md
starknet/Cargo.toml
starknet/src/lib.rs
starknet/src/node.rs
starknet/src/server/mod.rs
starknet/src/server/stream.rs
starknet/src/websocket.rs
starknet/tests/test_node.rs
starknet/tests/test_reorgs.rs
starknet/tests/test_websockets.rs

This commit adds the ability to ensure users are within their usage quota while
streaming. This is achieved by querying an external Quota service at a fixed
interval.

Add quota service

---

Cargo.lock
sinks/sink-console/CHANGELOG.md
sinks/sink-console/Cargo.toml
sinks/sink-mongo/CHANGELOG.md
sinks/sink-mongo/Cargo.toml
sinks/sink-parquet/CHANGELOG.md
sinks/sink-parquet/Cargo.toml
sinks/sink-postgres/CHANGELOG.md
sinks/sink-postgres/Cargo.toml
sinks/sink-webhook/CHANGELOG.md
sinks/sink-webhook/Cargo.toml

**Summary**
sink-console: v0.3.3
sink-mongo: v0.4.3
sink-parquet: v0.3.3
sink-postgres: v0.4.3
sink-webhook: v0.3.3

release: sinks

---

starknet/src/ingestion/config.rs
starknet/src/ingestion/started.rs
starknet/src/lib.rs
starknet/tests/test_node.rs
starknet/tests/test_reorgs.rs
starknet/tests/test_websockets.rs

starknet: add option to start ingestion at specific block

---

sinks/sink-common/src/connector.rs
sinks/sink-console/src/sink.rs
sinks/sink-mongo/src/sink.rs
sinks/sink-parquet/src/sink.rs
sinks/sink-postgres/src/sink.rs
sinks/sink-webhook/src/sink.rs

**Summary**
Implement the `Display` trait for `Context` to display the current's batch context in a human-friendly way.

sink: improve logging output

---

Cargo.lock
operator/CHANGELOG.md
operator/Cargo.toml
operator/examples/console.yml
operator/src/crd.rs
operator/src/reconcile.rs
operator/tests/test_controller.rs

operator: add support for private repositories
**Summary**
Authenticate with GitHub using personal access tokens.

operator: add support for private repositories

---

sinks/sink-common/src/error.rs
sinks/sink-console/src/lib.rs
sinks/sink-console/src/sink.rs
sinks/sink-mongo/src/lib.rs
sinks/sink-mongo/src/sink.rs
sinks/sink-mongo/tests/test_multi_collection.rs
sinks/sink-mongo/tests/test_sink.rs
sinks/sink-parquet/src/configuration.rs
sinks/sink-parquet/src/lib.rs
sinks/sink-parquet/src/parquet_writer.rs
sinks/sink-parquet/src/sink.rs
sinks/sink-parquet/tests/test_sink.rs
sinks/sink-postgres/src/configuration.rs
sinks/sink-postgres/src/lib.rs
sinks/sink-postgres/src/sink.rs
sinks/sink-postgres/tests/test_entity_mode_sink.rs
sinks/sink-postgres/tests/test_sink.rs
sinks/sink-webhook/src/configuration.rs
sinks/sink-webhook/src/lib.rs
sinks/sink-webhook/src/sink.rs
sinks/sink-webhook/tests/test_sink.rs

Refactor all sinks errors to `SinkError`

---

Cargo.lock
flake.lock
sinks/sink-postgres/src/configuration.rs
sinks/sink-postgres/tests/common/mod.rs
sinks/sink-postgres/tests/test_sink.rs
sinks/sink-webhook/src/sink.rs
sinks/sink-webhook/tests/test_sink.rs

- Update cargo dependencies
- sink-postgres: test unique columns
- sink-webhook: skip sending data if all values are null

Prepare sinks for release

---

Cargo.lock
starknet/CHANGELOG.md
starknet/Cargo.toml
starknet/src/stream/batch_producer.rs

- starknet: include transactions or events if reverted
- release: starknet

include reverted transactions

---

.github/workflows/cd-release.yml
.github/workflows/ci-check.yml
Cargo.lock
sinks/sink-console/CHANGELOG.md
sinks/sink-console/Cargo.toml

Release sink console v0.4.5

---

Cargo.lock
Cargo.toml
observability/Cargo.toml
observability/src/lib.rs
starknet/src/server/service.rs

Removes some of the unnecessary values set for the meter and the tracer + bumps the deps.
No testing set in place as this just modifies crate version. If needed can add some.

dev(obs): bump deps and removed unused

---

Cargo.lock
cli/CHANGELOG.md
cli/Cargo.toml

Create a new release for the cli since the type definitions for starknet
filters changed.

release: cli v0.5.1

---

Cargo.lock
script/Cargo.toml
script/src/script.rs
sinks/sink-common/src/connector/default.rs
sinks/sink-mongo/CHANGELOG.md
sinks/sink-mongo/Cargo.toml
sinks/sink-mongo/src/sink.rs

Users are reporting performance issues when using the MongoDB sink.
This PR adds more detailed traces to the sink to help us debug the
issue.

Add tracing to MongoDB Sink

---

Cargo.lock
beaconchain/Cargo.toml
beaconchain/src/filter/mod.rs
common/src/data_stream/stream.rs
common/src/query.rs
evm/Cargo.toml
evm/src/filter/mod.rs
protocol/proto/beaconchain/v2/filter.proto
protocol/proto/evm/v2/filter.proto
protocol/proto/starknet/v2/data.proto
protocol/proto/starknet/v2/filter.proto
starknet/Cargo.toml
starknet/src/filter/contract_change.rs
starknet/src/filter/mod.rs
starknet/src/filter/nonce_update.rs
starknet/src/filter/storage_diff.rs
starknet/src/filter/transaction.rs
starknet/src/fragment.rs
starknet/src/ingestion.rs
starknet/src/lib.rs
starknet/src/proto.rs
starknet/src/provider/models.rs

This PR introduces state update data to Starknet.
It also includes small changes to the `HeaderFilter` for all three networks.

Add state update data

---

Cargo.lock
beaconchain/Cargo.toml
beaconchain/src/ingestion.rs
common/src/compaction/group_builder.rs
common/src/dbg/index.rs
common/src/index.rs
common/src/query.rs
evm/Cargo.toml
starknet/Cargo.toml

Fix an issue with the Beacon Chain ingestion service generating blocks with missing indices for missed slots.

Fix Beacon Chain ingestion issues

---

.github/workflows/build.yml
.github/workflows/cd-check.yml
.github/workflows/cd-pipeline.yml
.github/workflows/cd-release.yml
.github/workflows/ci-check.yml
.github/workflows/ci-pipeline.yml
Cargo.lock
beaconchain/Cargo.toml
beaconchain/src/filter/mod.rs
common/src/query.rs
evm/Cargo.toml
evm/src/filter/mod.rs
starknet/Cargo.toml
starknet/src/filter/mod.rs

In some cases, it makes sense to allow an empty filter. This PR stops the DNA server from erroring in that case.

Allow empty filter if multiple filters specified

---

Cargo.lock
beaconchain/Cargo.toml
beaconchain/src/cli/start.rs
beaconchain/src/ingestion.rs
beaconchain/src/lib.rs
common/src/block_store.rs
common/src/data_stream/segment_stream.rs
common/src/file_cache.rs
common/src/object_store.rs
common/tests/test_ingestion_service.rs
evm/Cargo.toml
evm/src/ingestion.rs
starknet/Cargo.toml
starknet/src/ingestion.rs

This PR contains more performance improvements:
- Reduce fetched data in some cases.
- Use separate cache for groups. This will make group cache hit rate more predictable.
- Sample beacon chain validators. This drastically reduces data transmitted while losing very little information.
**All**
Changed:
- `DNA_CACHE_SIZE_DISK` -> `DNA_CACHE_DATA_DISK_SIZE`
- `DNA_CACHE_FILE_SIZE` -> `DNA_CACHE_DATA_FILE_SIZE`
- `DNA_CACHE_SIZE_MEMORY` -> `DNA_CACHE_DATA_MEMORY_SIZE`
New:
- `DNA_CACHE_INDEX_DISK_SIZE`
- `DNA_CACHE_INDEX_FILE_SIZE`
- `DNA_CACHE_INDEX_MEMORY_SIZE`
**Beacon Chain**
Removed:
- `BEACONCHAIN_INGEST_VALIDATORS`. Set `BEACON_SAMPLE_VALIDATORS` to `0` to disable ingesting validators.
New:
- `BEACON_SAMPLE_VALIDATORS`

Performance improvements

---

Cargo.lock
beaconchain/Cargo.toml
benchmark/src/lib.rs
common/src/data_stream/stream.rs
evm/Cargo.toml
observability/src/dna_fmt.rs
starknet/Cargo.toml

This PR creates a new release that fixes an issue sending the cursor of finalized/segmented blocks.

Release beta 23 with a minor bug fix

---

Cargo.lock
beaconchain/Cargo.toml
common/Cargo.toml
common/src/cli.rs
common/src/dbg/prefetch.rs
common/src/lib.rs
common/src/object_store/aws_s3.rs
common/src/object_store/azure_blob.rs
common/src/object_store/client.rs
common/src/object_store/error.rs
common/src/object_store/mod.rs
common/src/object_store/testing.rs
common/tests/test_ingestion_service.rs
common/tests/test_object_store.rs
evm/Cargo.toml
starknet/Cargo.toml

This PR adds support for the Azure Blob Storage backend.

Add support for Azure Blob Storage backend

---

Cargo.lock
beaconchain/Cargo.toml
common/src/lib.rs
common/src/object_store/aws_s3.rs
common/src/object_store/azure_blob.rs
common/src/object_store/client.rs
common/src/object_store/mod.rs
evm/Cargo.toml
starknet/Cargo.toml

This PR adds a check for the bucket to exist on startup. This is useful to help debugging access tokens in production.

Help debug S3 credentials
