apibara/dna

- Cargo.lock
- apibara/Cargo.toml
- apibara/src/configuration.rs
Getting the configuration only from the Toml file is not convenient and does not follow [the 12 factors app best practices](https://12factor.net/config).
Thankfully figments support multiple sources, including env variables.
> Feat: read prefixed env variables to get configuration

- core/proto/node.proto
- starknet/src/server.rs
Connect is a too generic name that can clash with autogenerated code.
> Rename Connect to StreamMessages

- Cargo.lock
- core/proto/node.proto
- examples/starknet-token-transfer/Cargo.toml
- examples/starknet-token-transfer/src/app.rs
- node/src/heartbeat.rs
- node/src/lib.rs
- node/src/processor.rs
- starknet/src/server.rs
This PR adds heartbeats to streams so that clients can check if the stream hang or it's still active.
The heartbeat interval is set at 30 seconds, but in the future it should be configurable.
> Add heartbeats to stream

- node/Cargo.toml
- starknet/Cargo.toml
The crate uses `tokio_stream::wrappers::BroadcastStream` but didn't have
the `sync` feature.
Importing the crate in an external project would fail compiling because
of this.
> node: add sync feature to tokio-stream

- .github/workflows/ci.yml
- core/proto/node.proto
- core/src/stream.rs
- node/src/input.rs
- node/src/message_stream.rs
- node/src/processor.rs
- node/src/server.rs
- starknet/README.md
- starknet/src/bin.rs
- starknet/src/block_builder.rs
- starknet/src/block_ingestion.rs
- starknet/src/node.rs
- starknet/src/server.rs
- starknet/tests/integration_test.rs
This PR adds support for requesting pending blocks to be included.
This is useful to mainnet projects, where blocks are produced very infrequently.
> Add pending blocks support

- starknet/proto/v1alpha2/filter.proto
- starknet/src/stream/block.rs
Most users need header information only if any other data matches.
This change introduces the concept of "weak" header: the header
is included only if any other filter matches.
> starknet: add weak header filter

- starknet/src/db/storage.rs
- starknet/src/ingestion/accepted.rs
- starknet/src/ingestion/started.rs
Removing a block from the canonical chain implies changing the
status to rejected. The trait method now does that automatically.
> starknet: reject block from canonical chain

- core/Cargo.toml
- node/Cargo.toml
- starknet/Cargo.toml
Update anyhow version to match the one used in the cairo repo https://github.com/starkware-libs/cairo/blob/5368d3147921ec3e34c59c84666978ada1979580/Cargo.toml#L41
> chore(starknet): match anyhow version with cairos package

- Cargo.lock
- starknet/src/healer.rs
- starknet/src/lib.rs
- starknet/src/node.rs
- starknet/src/server/health.rs
- starknet/src/server/mod.rs
- starknet/src/server/stream.rs
- starknet/src/stream/data.rs
- starknet/src/stream/filtered.rs
If the stream encounters any block whose status is not what it should be, try to heal it on the fly.
> Heal block status

- starknet/src/stream/block.rs
Some events were returned in the wrong order because receipts were considered to be ordered.
> starknet: sort receipts before filtering data

- .editorconfig
- starknet/src/stream/filtered.rs
This PR improves compatibility with starknet-devnet.
Devnet doesn't produce finalized blocks and so we need to handle
this case by sending accepted blocks.
> starknet: stream data from chain without finalized blocks

- starknet/src/ingestion/config.rs
- starknet/src/ingestion/mod.rs
- starknet/src/ingestion/subscription.rs
Change the ingestion code to simply pause ingestion when it encounters
an error. This means that users can keep streaming data even if there is
a network/node outage.
> starknet: pause ingestion on error

- README.md
- starknet/src/bin.rs
- starknet/src/node.rs
Add a new `--wait-for-rpc` flag to wait for the rpc to become available
before starting ingesting data.
> Add option to wait for rpc

- core/build.rs
The build was failing because of this flag not being present due to proto3
This just adds `.protoc_arg("--experimental_allow_proto3_optional")`
> adds --experimental_allow_proto3_optional

- core/proto/node/v1alpha2/stream.proto
- starknet/src/server/stream.rs
This PR add support to non bidirectional stream methods.
Close #94 
I didn't yet succeed to validate the correct behavior of my modification.
I think we could also reduce code duplication between `stream_data` and `stream_data_immutable`
> starknet: add non bidirectional stream methods

- core/src/node.rs
Add Deserialize for Cursor and DataFinality in case we need to
deserialize these values.
> core: implement Deserialize for Cursor and DataFinality

- .github/workflows/nix.yml
- Cargo.lock
- Cargo.toml
- sink-common/Cargo.toml
- sink-common/src/configuration.rs
- transformer/Cargo.toml
- transformer/src/lib.rs
- transformer/src/transformer.rs
- transformer/tests/test_transformer.rs
For production usage, we want to limit the resources users can use and
for this we use deno's permissions.
> Lock down deno permissions

- core/src/starknet/data.rs
- observability/src/lib.rs
- starknet/src/db/mod.rs
- starknet/src/db/state.rs
- starknet/src/db/storage.rs
- starknet/src/stream/batch_producer.rs
At the moment, some blocks have so many storage changes that trying to filter them sequentially results in very poor performance.
With this PR, we change the db layout to simplify filtering storage changes by contract address.
> Optimize storage changes access

- starknet/src/ingestion/accepted.rs
- starknet/src/lib.rs
- starknet/src/node.rs
- starknet/tests/test_node.rs
- starknet/tests/test_reorgs.rs
- starknet/tests/test_websockets.rs
**Summary**
Previously the value was hardcoded to 3 seconds because it made sense
for Starknet (public).
With Madara, this value is too high and needs to be customized based on
the chain's speed.
This PR adds a new `--head-refresh-internal-ms` flag to customize the
interval at which the ingestion components checks for new pending
blocks or heads.
> starknet: add flag to change head refresh interval

- .gitignore
- flake.nix
- nix/build.nix
**Summary**
This container contains the `apibara` binary, together with the builtin `apibara-sink-*` binaries.
Developers can use this container to run `apibara` without having to use a separate container for each sink type.
> Create `apibara-cli` docker image

- cli/src/main.rs
- sink-common/src/configuration.rs
- sink-common/src/lib.rs
**Summary**
This change is to reduce the confusion when accessing environment variables from Deno. Since Deno will show an error message mentioning `--allow-env`, it was confusing to explain that the flag is actually `--env-from-file` in Apibara. So, we rename the flag to match Deno's error message.
> Rename `--env-from-file` to `--allow-env`

- Cargo.lock
- Cargo.toml
- node/Cargo.toml
- node/src/stream/data.rs
- starknet/src/lib.rs
- starknet/src/node.rs
- starknet/src/server/mod.rs
- starknet/src/server/stream.rs
- starknet/src/websocket.rs
- starknet/tests/test_node.rs
- starknet/tests/test_reorgs.rs
- starknet/tests/test_websockets.rs
**Summary**
Unlimited streaming speed creates the issue where some users can exhaust the server's resources by streaming blocks at a very high rate. This commit adds a cli flag to limit the number of blocks per second per stream.
> starknet: Add cli flag to rate-limit the blocks per second per stream

- flake.nix
- nix/build.nix
**Summary**
Add a `-universal` derivation for each crate that patches the binary produced by nix to work on all linux platforms.
> Build universal linux binaries

- Cargo.lock
- Cargo.toml
- core/proto/starknet/v1alpha2/filter.proto
- core/proto/starknet/v1alpha2/starknet.proto
- starknet/src/provider.rs
- starknet/src/stream/batch_producer.rs
- starknet/tests/test_node.rs
- starknet/tests/test_reorgs.rs
**Summary**
Starknet v0.12.1 includes reverted transactions in blocks. This commit adds support for ingesting reverted transactions, but not for streaming them.
> Add support for reverted transactions and RPC v0.4.0

- Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
- cli/src/paths.rs
- cli/src/plugins.rs
- cli/src/run.rs
**Summary**
The plugin manager is used to install, list, update, and remove plugins. At the moment, the only plugin type is `sink`.
The manager only supports installing plugins from a local file.
> cli: Add plugin manager

- install/install.sh
**Summary**
While `darwin` seems to be popular, `macos` is the name used by Rust and so it's easier to use that name.
> installer: use macos as the name of desktop darwin

- nix/ci.nix
- sink-mongo/src/sink.rs
- sink-parquet/src/sink.rs
- sink-postgres/src/sink.rs
- sink-webhook/src/sink.rs
**Summary**
Change the sink logs to have somewhat the same output. Remove warning logs if the user passes an empty array since this is normal in practice.
> sink: normalize sink logs

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- sink-console/CHANGELOG.md
- sink-console/Cargo.toml
- sink-mongo/CHANGELOG.md
- sink-mongo/Cargo.toml
- sink-parquet/CHANGELOG.md
- sink-parquet/Cargo.toml
- sink-postgres/CHANGELOG.md
- sink-postgres/Cargo.toml
- sink-webhook/CHANGELOG.md
- sink-webhook/Cargo.toml
**Summary**
cli: v0.2.0
sink-console: v0.3.0
sink-mongo: v0.4.0
sink-parquet: v0.3.0
sink-postgres: v0.4.0
sink-webhook: v0.3.0
> release: cli, sink-console, sink-mongo, sink-parquet, sink-postgres, sink-webhook

- Cargo.lock
- sdk/src/lib.rs
- sink-common/src/configuration.rs
- sink-common/src/connector.rs
- sink-console/CHANGELOG.md
- sink-console/Cargo.toml
- sink-mongo/CHANGELOG.md
- sink-mongo/Cargo.toml
- sink-parquet/CHANGELOG.md
- sink-parquet/Cargo.toml
- sink-postgres/CHANGELOG.md
- sink-postgres/Cargo.toml
- sink-webhook/CHANGELOG.md
- sink-webhook/Cargo.toml
**Summary**
gRPC streams can hang without either side being notified. The DNA protocol
includes heartbeat messages to help detect this, but until now the sinks were
not taking advantage of this behaviour.
This commit stops the sink if it doesn't receive any message for a given amount of seconds.
> Add timeout waiting for stream messages

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/src/test/snapshot.rs
- sdk/src/lib.rs
- sink-common/src/configuration.rs
**Summary**
The default stream timeout was 0 seconds, which resulted in the stream being unusable. We change the default timeout to be 45 seconds.
> sdk: provide sensible stream timeout

- Cargo.lock
- sinks/sink-console/CHANGELOG.md
- sinks/sink-console/Cargo.toml
- sinks/sink-mongo/CHANGELOG.md
- sinks/sink-mongo/Cargo.toml
- sinks/sink-parquet/CHANGELOG.md
- sinks/sink-parquet/Cargo.toml
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
- sinks/sink-webhook/CHANGELOG.md
- sinks/sink-webhook/Cargo.toml
**Summary**
sink-console: v0.3.5
sink-mongo: v0.4.6
sink-parquet: v0.3.5
sink-postgres: v0.4.6
sink-webhook: v0.3.5
> release: sink-console, sink-mongo, sink-parquet, sink-postgres, sink-webhook

- Cargo.lock
- sinks/sink-common/src/configuration.rs
- sinks/sink-common/src/lib.rs
- sinks/sink-console/CHANGELOG.md
- sinks/sink-console/Cargo.toml
- sinks/sink-mongo/CHANGELOG.md
- sinks/sink-mongo/Cargo.toml
- sinks/sink-parquet/CHANGELOG.md
- sinks/sink-parquet/Cargo.toml
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
- sinks/sink-webhook/CHANGELOG.md
- sinks/sink-webhook/Cargo.toml
**Summary**
In some cases (e.g. Kubernetes), it's infeasible to allow access only to environment variables specified in a .env file.
This commit adds a new flag to allow access to the parent process environment variables.
> sink: allow access to parent's environment variables

- docs/integrations/mongo.mdx
- sinks/sink-mongo/src/configuration.rs
- sinks/sink-mongo/src/sink.rs
- sinks/sink-mongo/tests/common/mod.rs
- sinks/sink-mongo/tests/test_multi_collection.rs
- sinks/sink-mongo/tests/test_sink.rs
Users can now add a "collection" key to the value returned from the transform function to specify the name of the collection
Fixes #278
Replaces #280
>  Support writing to multiple collections in mongo

- Cargo.lock
- operator/CHANGELOG.md
- operator/Cargo.toml
- operator/src/bin.rs
- operator/src/configuration.rs
- operator/src/controller.rs
operator: optionally limit operator to a namespace
**Summary**
For production usage, users may need to configure the operator
differently based on the use. With this change, they can limit the
operator to a single namespace.
release: operator v0.2.1
> operator: optionally limit operator to a namespace

- Cargo.lock
- operator/CHANGELOG.md
- operator/Cargo.toml
- operator/src/crd.rs
operator: fix CRD capitalization
**Summary**
CRD was using snake case, but the k8s convention is to use camel case.
release: operator v0.2.2
> operator: fix CRD capitalization

- Cargo.lock
- Cargo.toml
- core/proto/starknet/v1alpha2/starknet.proto
- starknet/src/ingestion/config.rs
- starknet/src/provider.rs
starknet: update to RPC v0.6
**Summary**
RPC v0.6 is a big change, with new transaction types (V3) among other
things.
This commit tries to map new fields (like multi-currency fees) to the
old ones.
starknet: include transaction index in transaction
**Summary**
Transaction index can be used to generate a unique id or to order
events.
> starknet: update to RPC v0.6

- sinks/sink-common/src/connector.rs
- sinks/sink-common/src/status/client.rs
- sinks/sink-common/src/status/mod.rs
- sinks/sink-common/src/status/server.rs
- sinks/sink-common/src/status/service.rs
- sinks/sink-console/src/sink.rs
Publish sync related metrics to OTEL. Users can use this data to
generate grafana dashboards.
Additionally, move the status service to its dedicated task.
Previously, the indexer and the status service were running on the same
tokio task. This is an issue because the status service had to wait for
the DNA stream to finish producing messages before it could handle
updating the status. In practice, this resulted in annoying grpc timeout
errors for clients trying to access the sink status.
Moving the status service to its own task solves the issue.
> Improve sink status service

- sinks/sink-common/src/connector.rs
- sinks/sink-common/src/persistence/common.rs
- sinks/sink-common/src/persistence/default.rs
- sinks/sink-common/src/persistence/etcd.rs
- sinks/sink-common/src/persistence/fs.rs
- sinks/sink-common/src/persistence/mod.rs
- sinks/sink-common/tests/test_etcd_persistence.rs
**Summary**
Adding support for factories requires tracking the dynamic filter built
by listening to factory events. We are going to use the same persistence
mechanism used to track the indexer's cursor to track the filter.
This commit changes the data stored in the persistence layer to be a
struct that can be extended later.
> sink: refactor persistence to store state

- core/proto/node/v1alpha2/stream.proto
- core/proto/starknet/v1alpha2/starknet.proto
- core/src/node.rs
- node/src/stream/configuration.rs
- sdk/src/configuration.rs
- sdk/src/lib.rs
- starknet/src/stream/batch_producer.rs
- starknet/src/stream/cursor_producer.rs
**Summary**
To implement factories, we need a way to stream data in two separate but
synchronized streams.
This PR introduces the concept of "multi filter":
- clients enter multi-filter mode by specifying multiple filters in the
request. To keep backward compatibility, the server still accepts the
old requests.
- batch size must be 1.
- response includes one block for each filter (using the same field as
batched block data, hence why batch size must be 1).
- if no filter matches, the block/batch is skipped (like the standard
version).
- if a filter doesn't match, a block with all default values and `empty
= true` is inserted to keep ordering between blocks.
> starknet: implement multi-filter

- core/src/filter.rs
- core/src/lib.rs
- core/src/starknet/filter.rs
- examples/common/jediswap.js
- examples/console/starknet_factory.js
- examples/parquet/starknet_factory.js
- script/src/script.rs
- sinks/sink-common/src/connector.rs
**Summary**
This PR introduces factory mode. Developers can export a `factory`
callback from their script to enable this mode.
The `filter` returned by the `factory` callback is used to create the
"main" data stream, whose transformed output is passed to the
integration.
This commit is not concerned with correctly handling cursor and state
persistence between restarts, or combining the main filter.
> sink: implement factory mode

- Cargo.lock
- sinks/sink-common/src/connector/mod.rs
- sinks/sink-console/CHANGELOG.md
- sinks/sink-console/Cargo.toml
- sinks/sink-mongo/CHANGELOG.md
- sinks/sink-mongo/Cargo.toml
- sinks/sink-parquet/CHANGELOG.md
- sinks/sink-parquet/Cargo.toml
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
- sinks/sink-webhook/CHANGELOG.md
- sinks/sink-webhook/Cargo.toml
sink: adjust retry behaviour
**Summary**
Reduce the wait time between retries to a minute at most. Ensure that
the indexer exits for all non-temporary errors.
release: sink-{console, mongo, parquet, postgres, webhook}
**Summary**
sink-console: v0.4.0
sink-mongo: v0.5.0
sink-parquet: v0.4.0
sink-postgres: v0.5.0
sink-webhook: v0.4.0
> sink: adjust retry behaviour

- Cargo.lock
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
- sinks/sink-postgres/src/sink.rs
sink-postgres: reconnect if client becomes disconnected
**Summary**
When running for long periods of time (like in production), the client
may disconnect from the server. This causes all queries to fail and the
indexer to be stuck ~30m until it restarts.
This commit ensures that the client is connected before executing a
query.
release: sink-postgres
**Summary**
sink-postgres: v0.5.1
> sink-postgres: reconnect if client becomes disconnected

- script/src/script.rs
- sinks/sink-common/src/configuration.rs
- sinks/sink-console/src/bin.rs
- sinks/sink-mongo/src/bin.rs
- sinks/sink-parquet/src/bin.rs
- sinks/sink-postgres/src/bin.rs
- sinks/sink-webhook/src/bin.rs
**Summary**
More complex indexers require users to interact with external APIs.
It's time to let indexers communicate with the external world.
> sink: add flag to allow network access

- examples/parquet/starknet_factory.js
- sinks/sink-parquet/src/configuration.rs
- sinks/sink-parquet/src/sink.rs
- sinks/sink-parquet/tests/test_sink.rs
**Summary**
Add a new option to write to multiple datasets with one indexer.
> sink-parquet: multiple datasets from one indexer

- Cargo.lock
- sinks/sink-console/CHANGELOG.md
- sinks/sink-console/Cargo.toml
- sinks/sink-mongo/CHANGELOG.md
- sinks/sink-mongo/Cargo.toml
- sinks/sink-parquet/CHANGELOG.md
- sinks/sink-parquet/Cargo.toml
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
- sinks/sink-webhook/CHANGELOG.md
- sinks/sink-webhook/Cargo.toml
**Summary**
sink-console: v0.4.1
sink-mongo: v0.5.1
sink-parquet: v0.4.1
sink-postgres: v0.5.2
sink-webhook: v0.4.1
> release: sink-{console, mongo, parquet, postgres, webhook}

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/src/run.rs
- script/src/script.rs
- sinks/sink-console/CHANGELOG.md
- sinks/sink-console/Cargo.toml
- sinks/sink-mongo/CHANGELOG.md
- sinks/sink-mongo/Cargo.toml
- sinks/sink-parquet/CHANGELOG.md
- sinks/sink-parquet/Cargo.toml
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
- sinks/sink-webhook/CHANGELOG.md
- sinks/sink-webhook/Cargo.toml
cli: propagate --allow-net flag
sink: --allow-net="" allows any host
**Summary**
This change ensures that the --allow-net flag works in environments were
changing the command line arguments is not feasible/recommended (e.g.
docker containers).
Fix #312
release: cli, sink-{console, mongo, parquet, postgres, webhook}
**Summary**
cli: v0.4.2
sink-console: v0.4.2
sink-mongo: v0.5.2
sink-parquet: v0.4.2
sink-postgres: v0.5.3
sink-webhook: v0.4.2
> Improve --allow-net flag

- Cargo.lock
- sinks/sink-common/Cargo.toml
- sinks/sink-common/src/configuration.rs
- sinks/sink-common/src/persistence/mod.rs
- sinks/sink-common/src/persistence/redis.rs
- sinks/sink-common/tests/test_redis_persistence.rs
This PR adds redis persistence as an option.
Note that locking is not yet implemented since it's not that urgent
Fixes #314
> sink: add redis persistence

- starknet/src/node.rs
**Summary**
The mainnet database is getting closer to 256Gb, so it's time to bump
the maximum size again.
> starknet: increase database size to 512Gb

- Cargo.lock
- cli/src/run.rs
- script/src/script.rs
- sinks/sink-common/src/configuration.rs
- sinks/sink-console/CHANGELOG.md
- sinks/sink-console/Cargo.toml
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
sink: add filesystem read/write permissions
**Summary**
Allow indexers to read and write data from the filesystem.
Filesystem access is granted with the `--allow-read` and `--allow-write`
flags.
release: sink-{console, postgres}
**Summary**
sink-console: v0.4.4
sink-postgres: v0.5.5
> sink: add filesystem read/write permissions

- Cargo.lock
- Cargo.toml
- sinks/sink-parquet/Cargo.toml
- sinks/sink-parquet/src/configuration.rs
- sinks/sink-parquet/src/lib.rs
- sinks/sink-parquet/src/parquet_writer.rs
- sinks/sink-parquet/src/sink.rs
- sinks/sink-parquet/tests/test_sink.rs
- starknet/tests/test_node.rs
- starknet/tests/test_reorgs.rs
- starknet/tests/test_websockets.rs
Simply by setting the `--output-dir` to an S3 URL like `s3://bucket/`,
the S3 credentials will be loaded using the default AWS credentials provider chain
> parquet: support writing parquet files to S3

- sinks/sink-postgres/src/configuration.rs
- sinks/sink-postgres/src/sink.rs
- Added  `pub unique_columns: bool` to `SinkPostgresConfiguration` in `configuration`.
- Added `pub unique_columns: Option<bool>,` to `SinkPostgresOptions`
- Modified `query` variable in `new` function of StandardSink to be conditionally set based on unique_columns value.
All sink postgres test are passing using local docker container
Tested with real data, working as expected
> Added unique colums option to sink postgres

- Cargo.lock
- sinks/sink-mongo/CHANGELOG.md
- sinks/sink-mongo/Cargo.toml
- sinks/sink-parquet/CHANGELOG.md
- sinks/sink-parquet/Cargo.toml
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
- sinks/sink-webhook/CHANGELOG.md
- sinks/sink-webhook/Cargo.toml
- sink-mongo: v0.6.0
- sink-parquet: v0.5.0
- sink-postgres: v0.6.0
- sink-webhook: v0.5.0
> release: sink-{mongo, parquet, postgres, webhook}

- flake.lock
- flake.nix
**Summary**
NixOS 23.11 uses a version of GLIBC that's higher than the version
included in Ubuntu 22.04. This makes all packages compiled in the CI not
compatible with that version of Ubuntu.
This commit downgrades the nixpkgs version to use an older version of
GLIBC.
> Downgrade nixpkgs to 23.05

- sinks/sink-mongo/src/sink.rs
- sinks/sink-mongo/tests/test_sink.rs
This PR fixes a MongoDB error if the sink received no data from the
transform function. This usually happens once the indexer reaches
the tip of the chain.
- Run an indexer and wait until it reaches an accepted or pending block.
- Before this PR, the indexer prints an error. After this PR the indexer works
as expected.
> sink-mongo: skip mongo operations if no data provided

- .github/workflows/cd-release.yml
- .github/workflows/ci-check.yml
- Cargo.lock
- sinks/sink-console/CHANGELOG.md
- sinks/sink-console/Cargo.toml
Release `sink-console` v0.4.5 to test the release process end to end.
> Release sink-console 0.4.5

- Cargo.lock
- examples/mongo/starknet_to_mongo.js
- sinks/sink-common/src/connector/default.rs
- sinks/sink-common/src/connector/sink.rs
- sinks/sink-common/src/sink.rs
- sinks/sink-mongo/CHANGELOG.md
- sinks/sink-mongo/Cargo.toml
- sinks/sink-mongo/src/configuration.rs
- sinks/sink-mongo/src/sink.rs
- sinks/sink-mongo/tests/test_multi_collection.rs
- sinks/sink-mongo/tests/test_sink.rs
By default, MongoDB handles updating pending data by removing the previous call
data and inserting the new data after that. Sometimes this results in data
"flashing".
This PR adds support for replacing pending data in one transaction. Notice
that this feature requires a special deployment of MongoDB (with replication)
and so it cannot be turned on by default.
- Deploy a MongoDB database with replication support.
- Run an indexer that inserts data at every block, for example the ETH
transfers example in the repo. Use the new `--replace-data-inside-transaction=true`
flag.
- Data is now always consistent.
> Use transactions to replace pending data in MongoDB sink

- charts/operator/.helmignore
- charts/operator/Chart.yaml
- charts/operator/README.md
- charts/operator/crds/custom-resource-definitions.yaml
- charts/operator/templates/NOTES.txt
- charts/operator/templates/_helpers.tpl
- charts/operator/templates/deployment.yaml
- charts/operator/templates/rbac-resources.yaml
- charts/operator/templates/service-account.yaml
- charts/operator/templates/tests/indexers.yaml
- charts/operator/values.yaml
- nix/crates.nix
The Apibara Operator is the easiest way to run Apibara indexers on Kubernetes.
The operator doesn't have any complex dependencies or requirements, but
requires configuring the service account correctly which can be difficult to
do.
- Start a `minikube` cluster.
- Create a namespace for the tests, e.g. `kubectl create namespace test-ns`.
- Install the chart, enabling tests. Notice you also need an Apibara API Key if
you want the indexer to run properly.
```
helm install my-test oci://quay.io/apibara-charts/operator \
--namespace=test-ns \
--set-json 'customArgs=["start", "--namespace=test-ns"]' \
--set-json='test.enabled=true' \
--set-string='test.apiKey=dna_xxx'
```
- Verify that the indexer is running correctly. `kubectl get pods -n test-ns`.
> charts: add operator helm chart

- Cargo.lock
- cli/CHANGELOG.md
- cli/Cargo.toml
- cli/src/test/compare.rs
- cli/src/test/mod.rs
- cli/src/test/run.rs
- cli/src/test/snapshot.rs
- examples/common/starknet.js
- sinks/sink-common/src/configuration.rs
One obstacle to the adoption of the `apibara test` command was that floating
point numbers were compared using strict equality. This resulted in _a lot_ of
false positives.
We add a new option to snapshots to control the floating point precision
(specifying the number of decimals to compare) used for equality comparison.
After generating the snapshot, users can edit it to change the
`testOptions.floatingPointDecimals` option to the required precision.
You can test by running the `apibara test` command on one of the example indexers:
- `cargo run -p apibara-cli -- test examples/postgres/starknet_to_postgres.js`.
- Open `snapshots/starknet_to_postgres.json` and check the `testOptions` section.
- Update that value to the desired number of decimals.
- Rerun the test and verify it succeeds.
> cli: control fp precision in tests

- starknet/Cargo.toml
- starknet/src/bin.rs
This PR makes the allocator used by the Starknet DNA server configurable.
Developers can disable jemalloc by building the project with the
`--disable-default-features` flag.
> starknet: add jemalloc feature

- Cargo.lock
- script/src/script.rs
- sinks/sink-console/CHANGELOG.md
- sinks/sink-console/Cargo.toml
- sinks/sink-mongo/CHANGELOG.md
- sinks/sink-mongo/Cargo.toml
- sinks/sink-parquet/CHANGELOG.md
- sinks/sink-parquet/Cargo.toml
- sinks/sink-postgres/CHANGELOG.md
- sinks/sink-postgres/Cargo.toml
- sinks/sink-webhook/CHANGELOG.md
- sinks/sink-webhook/Cargo.toml
This PR adds a shortcut to allow accessing all environment variables by
specifying an empty string.
> Allow all environment variables

- Cargo.lock
- starknet/CHANGELOG.md
- starknet/Cargo.toml
- starknet/src/ingestion/accepted.rs
Some users reported an `InconsistentDatabase` error when running
`apibara-starknet` together with devnet and mainnet forking.
This issue was caused by the ingestion service expecting blocks to
be ingested sequentially, starting from block 0.
This fix changes the ingestion service to consider the specified starting block
(if any) as finalized.
- Start `starknet-devnet-rs` with mainnet forking (e.g. `--chain-id MAINNET --fork-block 657000`)
- Start `apibara-starknet` ingesting data from devnet and by setting `--dangerously-override-ingestion-start-block=657065`
Notice how before this PR the ingestion process fails, but with this patch it works.
> Fix crash when overriding starking block

- Cargo.lock
- Cargo.toml
- beaconchain/Cargo.toml
- common/src/file_cache.rs
- common/src/server/service.rs
- evm/Cargo.toml
- observability/Cargo.toml
- observability/src/lib.rs
- starknet/Cargo.toml
Start exporting traces from Foyer.
> Export cache traces

- .config/nextest.toml
- Cargo.lock
- Cargo.toml
- beaconchain/Cargo.toml
- beaconchain/src/provider/http.rs
- common/Cargo.toml
- common/src/chain.rs
- common/src/data_stream/stream.rs
- common/src/ingestion/mod.rs
- common/src/ingestion/service.rs
- common/src/ingestion/state_client.rs
- common/tests/test_ingestion_service.rs
- evm/Cargo.toml
- evm/src/ingestion.rs
- evm/src/provider/http.rs
- evm/src/provider/mod.rs
- flake.lock
- flake.nix
- nix/crates.nix
- starknet/Cargo.toml
- starknet/src/ingestion.rs
- starknet/src/provider/http.rs
- starknet/src/provider/mod.rs
This PR makes some changes to how reorg are tested handled.
The ingestion service can now fully recover from online and offline reorgs.
The PR tests reorgs using anvil. The same strategy can be used to test locally.
> Test and improve reorg handling

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/cli.rs
- common/src/lib.rs
- etcd/src/client.rs
- evm/Cargo.toml
- starknet/Cargo.toml
The Etcd client acquires an authentication upon connection. This token is short lived (default to 5 minutes) and for this reason it needs to be renewed periodically or the client will error.
We are seeing this issue in production, with the DNA process restarting every 5 minutes or so.
> Periodically renew ETCD token

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/chain.rs
- common/src/chain_view/full.rs
- common/src/chain_view/mod.rs
- common/src/chain_view/view.rs
- common/src/compaction/group.rs
- common/src/compaction/segment.rs
- common/src/core.rs
- common/src/data_stream/stream.rs
- common/src/server/service.rs
- evm/Cargo.toml
- protocol/proto/dna/v2/stream.proto
- starknet/Cargo.toml
This PR improves on the starting cursor handling by:
- be less strict when comparing cursors by ignoring any 0 prefix in the hash.
- return the hash of the canonical block on error.
- signal to user whether the data is a backfill or live block.
> Improve starting cursor handling

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/compaction/group.rs
- common/src/compaction/group_builder.rs
- evm/Cargo.toml
- evm/src/ingestion.rs
- evm/src/proto.rs
- protocol/proto/evm/v2/data.proto
- protocol/proto/starknet/v2/data.proto
- starknet/Cargo.toml
- starknet/src/ingestion.rs
- starknet/src/proto.rs
Fix issues with missing data caused by group compaction. This was caused by the compaction not considering that segments include data up to the end of the segment range.
Also add a transaction-local index to events, messages, and logs.
> Fix issues with missing data

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/data_stream/stream.rs
- evm/Cargo.toml
- starknet/Cargo.toml
This PR fixes a couple of small things at the chain's head:
- empty block (if requested) are sent only at the chain's tip.
- heartbeats are sent when scan operations are taking too long.
> Fix behaviour at chain's head

- Cargo.lock
- beaconchain/Cargo.toml
- beaconchain/src/provider/http.rs
- beaconchain/src/provider/models.rs
- evm/Cargo.toml
- starknet/Cargo.toml
This PR improves compatibility with Beacon Chain RPCs by handling the case of pre-deneb blocks.
Some nodes (e.g. Erigon v3) return an empty list, while others return a 400 or 404 response.
> Improve beacon chain blob endpoint compatibility

- Cargo.lock
- Cargo.toml
- beaconchain/Cargo.toml
- common/Cargo.toml
- common/src/block_store.rs
- common/src/compaction/group.rs
- common/src/compaction/group_builder.rs
- common/src/compaction/segment.rs
- common/src/compaction/segment_builder.rs
- evm/Cargo.toml
- starknet/Cargo.toml
This PR speeds up compaction 10x to 100x by fetching blocks/segments in parallel.
It uses a `FuturesOrderedBounded` queue to limit the number of concurrent fetches to a reasonable number (128) even with a larger segment size.
> Speedup compaction

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/data_stream/metrics.rs
- common/src/data_stream/mod.rs
- common/src/data_stream/segment_access.rs
- common/src/data_stream/segment_stream.rs
- common/src/data_stream/stream.rs
- common/src/dbg/prefetch.rs
- common/src/server/cli.rs
- common/src/server/mod.rs
- common/src/server/service.rs
- evm/Cargo.toml
- flake.nix
- starknet/Cargo.toml
This PR fixes a bug in the data stream that resulted in blocks before the specified starting cursor to be sent.
We also add missing data stream metrics and make the prefetch queue size configurable.
> Minor data stream fixes

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/data_stream/segment_stream.rs
- common/src/data_stream/stream.rs
- common/src/file_cache.rs
- common/src/query.rs
- evm/Cargo.toml
- observability/src/lib.rs
- starknet/Cargo.toml
This PR includes some small changes that result in increased performance.
- Prefetch segment groups while streaming. This was previously the bottleneck.
- Enable cache compression to store more groups/segments/blocks on disk.
- Use S3 Fifo cache admission.
We also change the default filter behaviour to always send the tip of the chain.
> Minor performance improvements

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/block_store.rs
- common/src/chain_store.rs
- common/src/data_stream/metrics.rs
- common/src/data_stream/segment_access.rs
- common/src/data_stream/segment_stream.rs
- common/src/data_stream/stream.rs
- common/src/file_cache.rs
- common/tests/test_ingestion_service.rs
- evm/Cargo.toml
- starknet/Cargo.toml
This PR is in preparation of the upcoming changes to the file cache. We record better metrics so that we can then measure the impact of our changes.
- Record segment and group download and wait times.
- Record group cache hit.
> Improve segment stream metrics

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/block_store.rs
- common/src/compaction/metrics.rs
- common/src/compaction/mod.rs
- common/src/compaction/prune.rs
- common/src/compaction/service.rs
- common/src/ingestion/state_client.rs
- common/src/object_store/aws_s3.rs
- common/src/object_store/azure_blob.rs
- common/src/object_store/client.rs
- common/src/object_store/mod.rs
- evm/Cargo.toml
- starknet/Cargo.toml
This PR improves the compaction service to also prune blocks that now belong to a segment that has been grouped.
This blocks are not needed and can be safely removed, reducing data stored on S3 by ~50%.
> Prune grouped/segmented blocks

- Cargo.lock
- Cargo.toml
- beaconchain/Cargo.toml
- beaconchain/src/proto.rs
- beaconchain/src/provider/models.rs
- common/tests/test_ingestion_service.rs
- evm/Cargo.toml
- evm/src/proto.rs
- evm/src/provider/http.rs
- evm/src/provider/models.rs
- protocol/proto/evm/v2/data.proto
- protocol/src/beaconchain.rs
- protocol/src/evm.rs
- starknet/Cargo.toml
This PR updates the EVM and Beacon Chain types to the latest release of Alloy.
Most notably, it includes the `requests_hash` field in the block header.
> Update alloy and EVM/Beaconchain types

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/chain.rs
- common/src/chain_view/sync.rs
- common/src/chain_view/view.rs
- common/src/data_stream/stream.rs
- common/src/object_store/azure_blob.rs
- develop/docker-compose.etcd.yaml
- develop/docker-compose.no-etcd.yaml
- evm/Cargo.toml
- starknet/Cargo.toml
This PR fixes a couple of minor DNA stream server reliability issues:
- Correctly detect cursor _siblings_ on stream start. Previously, the function was returning the _reorg target_ cursors.
- Keep the stream server running when the etcd client disconnects. Now, the server keeps streaming historical data to clients and will resume serving live data once the etcd state client comes back online.
> Fix DNA stream server reliability issues

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/data_stream/stream.rs
- evm/Cargo.toml
- starknet/Cargo.toml
Previously, the pending block was considered "live" and so, if the user
requested to receive all live blocks, was sent even if empty.
This caused an issue when blocks `n` and `n+1` were discovered by the service
at the same time, since the client never received the accepted version of `n`.
This PR changes the live block behaviour to the following:
- pending blocks are sent only if they contain data.
- accepted blocks are sent if empty, if the client requested it.
We tested this by listening by running an indexer with the following filter:
```ts
const filter = {
header: "on_data_or_on_new_block",
logs: [
{
// wBTC on Ethereum mainnet.
address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
},
],
};
```
This filter occasionally produces pending data, but not always.
The following run trace …
> Change pending block to not be considered live

- Cargo.lock
- beaconchain/Cargo.toml
- common/src/data_stream/stream.rs
- evm/Cargo.toml
- starknet/Cargo.toml
The current implementation sends an empty block if joins are present.
This PR fixes that, sending blocks only if there is data.
> Avoid sending empty block with joins

- sdk/src/auth.rs
* When working with the indexer, I could not spawn the stream processing in a new tokio thread cause `Send` & `Sync` were missing as trait constraints.
* Used my fork for our project & it compiled correctly with those additions.
> chore: Added `Send + Sync` for `BearerTokenProvider` & `BearerTokenError` dyn errors
